import { NextResponse, NextRequest } from 'next/server';
import { supabase } from '@/lib/supabase';

/**
 * GET route querying historical reports generated by the teacher's active host_id.
 * Operates in two database steps: resolving owned meetings first, then mapping reports.
 */
export async function GET(req: NextRequest) {
  try {
    // Parse the host_id identifier representing the current teacher
    const host_id = req.nextUrl.searchParams.get('host_id');

    // Reject immediately if no verification criteria provided
    if (!host_id) {
      return NextResponse.json({ ok: false, error: 'Unauthorized: No host_id provided' }, { status: 401 });
    }

    // Step 1 & 2: First-Pass Resolution
    // Query host_meetings to obtain a complete array of all meeting_ids owned by this teacher
    // We cannot query the report directly because ownership mapping routes through host_meetings.
    const { data: hostMatches, error: hostError } = await supabase
      .from('host_meetings')
      .select('meeting_id')
      .eq('host_id', host_id);

    if (hostError) {
      console.error('[Download Report API] Error querying host_meetings:', hostError);
      return NextResponse.json({ ok: false, error: hostError.message }, { status: 500 });
    }

    // If there're no matches, safely abort without throwing error on subsequent missing maps
    if (!hostMatches || hostMatches.length === 0) {
      return NextResponse.json({ 
        ok: true,
        data: []
      });
    }

    // Strip out the array structure objects into a flat array of id strings required for PostgreSQL an '.in()' query.
    const meetingIds = hostMatches.map(match => match.meeting_id);

    // Step 3: Fetch Reporting Metadata payload details
    // Query group_report where the linked session_id exists ANYWHERE within the extracted meetingIds array
    const { data: rawData, error: reportError } = await supabase
      .from('group_report')
      .select('file_name, session_id, generated_date, generated_time')
      .in('session_id', meetingIds);

    if (reportError) {
      console.error('[Download Report API] Error fetching reports:', reportError);
      return NextResponse.json({ ok: false, error: reportError.message }, { status: 500 });
    }

    // Wrap the result payload to guarantee array parity structurally, regardless of rows returned
    return NextResponse.json({ 
        ok: true, 
        data: rawData || []
    });

  } catch (err: any) {
    // Outermost catch block encapsulating networking mismatches
    console.error('[Download Report API] Unexpected error:', err);
    return NextResponse.json({ ok: false, error: err.message || 'Internal Server Error' }, { status: 500 });
  }
}